/*
	Name:			XenoN Core 2
	Version:		2.0.0.0 Frozen Eye
	Update:			2011-06-04
	Copyright:		Copyright © 2007-2011 XenoN Core by PsichiX. All rights reserved.
	Author:			PsichiX
	Website:		http://www.xenon.psichix.com
	Description:	XenoN Core 4D World Engine
*/

/*
	== EN ==
	This file is part of Xenon Core Engine.
	You may distribute it further, but you can not modify it.
	Please do not use in modified form.
	The principles of XenoN Core License available in the file LICENSE_CORE_EN.TXT or visit: http://www.xenon.psichix.com.

	== PL ==
	Ten plik jest czescia XenoN Core Engine.
	Mozesz go rozpowszechniac dalej, jednak nie mozesz go modyfikowac.
	Nalezy uzytkowac w nie zmodyfikowanej formie.
	Nalezy przestrzegac zasad Licencji XenoN Core dostepnej w pliku LICENSE_CORE_PL.TXT oraz na stronie: http://www.xenon.psichix.com.
*/


/*
	MODULES:
		Photon		- Graphics
		Chaos		- Physics
		Psyche		- Artificial Intelligence
		TimeBridge	- Time Control
		Echo		- Audio
		Ether		- Network
*/

#ifndef _XENON_CORE_2_H_
#define _XENON_CORE_2_H_

#include "XenonCore2Options.h"
#ifndef XE_COMPILE_NO_WINDOWS_H
#include <windows.h>
#endif // XE_COMPILE_NO_WINDOWS_H
//#define XE_NOT_USE_LIBRARY
//#define XE_COMPILE_NOT_USE_CONSOLE

/*!
\namespace XeCore				Przestrzen nazw XenoN Core.
\namespace XeCore::Photon		Przestrzen nazw modulu Photon.
\namespace XeCore::Chaos		Przestrzen nazw modulu Chaos.
\namespace XeCore::Psyche		Przestrzen nazw modulu Psyche.
\namespace XeCore::TimeBridge	Przestrzen nazw modulu TimeBridge.
\namespace XeCore::Ether		Przestrzen nazw modulu Ether.
\namespace XeCore::Echo			Przestrzen nazw modulu Echo.
\namespace XeCore::Misc			Przestrzen nazw modulu roznosci.
*/

/*--- Mode ---*/
#ifdef XE_USE_STATIC_DEV
#define XE_COMPILE_STATIC
#endif // XE_USE_STATIC_DEV
#ifndef XE_COMPILE_EXPORT
#ifndef XE_COMPILE_STATIC
#ifndef _DEBUG
#pragma comment(lib,"XeCore/XenonCore2.lib")
#else // _DEBUG
#pragma comment(lib,"XeCore/XenonCore2-d.lib")
#endif // _DEBUG
#else // XE_COMPILE_STATIC
#ifndef _DLL
#ifndef _DEBUG
#pragma comment(lib,"XeCore/XenonCore2-MT.lib")
#else // _DEBUG
#pragma comment(lib,"XeCore/XenonCore2-MTd.lib")
#endif // _DEBUG
#else // _DLL
#ifndef _DEBUG
#pragma comment(lib,"XeCore/XenonCore2-MD.lib")
#else // _DEBUG
#pragma comment(lib,"XeCore/XenonCore2-MDd.lib")
#endif // _DEBUG
#endif // _DLL
#endif // XE_COMPILE_STATIC
#endif // XE_COMPILE_EXPORT
#ifdef XE_COMPILE_STATIC
#define XE_CALLTYPE _cdecl
#define XE_IMPEX
#else // XE_COMPILE_STATIC
#define XE_CALLTYPE __stdcall
#ifdef XE_COMPILE_EXPORT
#define XE_IMPEX extern "C" __declspec(dllexport)
#else
#define XE_IMPEX extern "C" __declspec(dllimport)
#endif // XE_COMPILE_EXPORT
#endif // XE_COMPILE_STATIC

/*--- Misc Definitions ---*/
#define PI 3.1415926535897932384626433832795
#define cstring char*
#define MEMRANGESIZE(firstvar,lastvar)				(((unsigned int)&(lastvar))-((unsigned int)&(firstvar))+sizeof(lastvar))

/*--- XE_RES_* ---*/
#define XE_RES_XENON	1024

#define XE_RES_SPLASH	1
#define XE_RES_INTRO	2

/*--- XE_BASE_* ---*/
#define XE_BASE_BIN		2
#define XE_BASE_OCT		8
#define XE_BASE_DEC		10
#define XE_BASE_HEX		16

/*--- XE_FLAG_* ---*/
#define	XE_FLAG_EMPTY					0x00000000
#define	XE_FLAG_ALL						0xFFFFFFFF
#define	XE_FLAG_SWAP					0x00000001
#define	XE_FLAG_COLORBUFF				0x00000002
#define	XE_FLAG_DEPTHBUFF				0x00000004
#define	XE_FLAG_STENCILBUFF				0x00000008
#define	XE_FLAG_ACCUMBUFF				0x00000010
#define	XE_FLAG_TRANSFORMIDENT			0x00000020
#define	XE_FLAG_PREMULTALPHA			0x00000040
#define XE_FLAG_SUBSTANCE_SOLID_RANGE	0x00000001
#define XE_FLAG_SUBSTANCE_SOLID_SURFACE	0x00000002
#define XE_FLAG_X						0x00000001
#define XE_FLAG_Y						0x00000002
#define XE_FLAG_Z						0x00000004
#define XE_FLAG_W						0x00000008

//! \namespace XeCore Przestrzen nazw XenoN Core
namespace XeCore
{

/*--- Data types ---*/
//! 32 bit pointer
typedef void* XePointer;
//! 8 bit signed
typedef char XeChar;
//! 8 bit unsigned
typedef unsigned char XeByte;
//! 16 bit signed
typedef short XeShort;
//! 16 bit unsigned
typedef unsigned short XeWord;
//! 32 bit signed
typedef int XeInteger;
//! 32 bit unsigned
typedef unsigned int XeDword;
//! 32 bit float
typedef float XeHalf;
//! 64 bit float
typedef double XeReal;
//! 32 bit handle
typedef XeDword XeHandle;

/*--- XeEstate ---*/
//! Zmienne stanu silnika
#define XE_NOONE (XeCore::XeEstate)-1
#define XE_NULL (XeCore::XeEstate)0
enum XeEstate
{
XE_FALSE,
XE_TRUE,
XE_SINGLE,
XE_DOUBLE,
XE_POINTS,
XE_LINES,
XE_LINELOOP,
XE_LINESTRIP,
XE_TRIANGLES,
XE_TRIANGLESTRIP,
XE_TRIANGLEFAN,
XE_QUADS,
XE_QUADSTRIP,
XE_POLYGON,
XE_FLUSH,
XE_FINISH,
XE_RENDERTARGET,
XE_FRAMEBUFFER,
XE_VERTEXBUFFER,
XE_SHADER,
XE_TEXTURE,
XE_DISPLAYLIST,
XE_SUBSTANCE,
XE_RAY,
XE_COVALENCE_FORCE,
XE_FORCE,
XE_SURFACE,
XE_PARTICLE,
XE_GLOBAL_FORCE,
XE_BLACK_HOLE,
XE_WAVE_FORCE,
XE_PSYCHE,
XE_DNA,
XE_DNA_BRAIN,
XE_DNA_CELLS,
XE_DNA_MUSCLES,
XE_DNA_SKIN,
XE_DNA_BODY_TEXTURE,
XE_SOCKET,
XE_RENDERTARGET_COUNT,
XE_FRAMEBUFFER_COUNT,
XE_VERTEXBUFFER_COUNT,
XE_SHADER_COUNT,
XE_TEXTURE_COUNT,
XE_DISPLAYLIST_COUNT,
XE_SUBSTANCE_COUNT,
XE_RAY_COUNT,
XE_COVALENCE_FORCE_COUNT,
XE_FORCE_COUNT,
XE_SURFACE_COUNT,
XE_PARTICLE_COUNT,
XE_GLOBAL_FORCE_COUNT,
XE_BLACK_HOLE_COUNT,
XE_WAVE_FORCE_COUNT,
XE_PSYCHE_COUNT,
XE_DNA_COUNT,
XE_SOCKET_COUNT,
XE_1D,
XE_2D,
XE_3D,
XE_4D,
XE_CUBE,
XE_CUBE_POS_X,
XE_CUBE_NEG_X,
XE_CUBE_POS_Y,
XE_CUBE_NEG_Y,
XE_CUBE_POS_Z,
XE_CUBE_NEG_Z,
XE_DATA,
XE_FRONT_LEFT,
XE_FRONT_RIGHT,
XE_BACK_LEFT,
XE_BACK_RIGHT,
XE_ENGINE_NAME,
XE_ENGINE_CODENAME,
XE_ENGINE_CREATOR,
XE_ENGINE_VERSION,
XE_ENGINE_DESCRIPTION,
XE_ENGINE_COPYRIGHT,
XE_ENGINE_OWNER,
XE_ENGINE_COMPILE_OPTIONS,
XE_DRAW_TO_WINDOW,
XE_DRAW_TO_LAYER,
XE_RENDER_VENDOR,
XE_RENDER_RENDERER,
XE_RENDER_VERSION,
XE_RENDER_EXTENSIONS,
XE_RENDER_MODE,
XE_RENDER_FORMAT_RGBA,
XE_RENDER_FORMAT_DEPTH,
XE_RENDER_FORMAT_STENCIL,
XE_RENDER_VSYNC_MODE,
XE_RENDER_ORIENTATION,
XE_RENDER_CLOCKWISE,
XE_RENDER_COUNTERCLOCKWISE,
XE_RENDER_TEXT_SETTINGS,
XE_RENDER_TEXT_SIZE_X,
XE_RENDER_TEXT_SIZE_Y,
XE_RENDER_TEXT_SEP_X,
XE_RENDER_TEXT_SEP_Y,
XE_RENDER_TEXT_NEWLINE,
XE_RENDER_MASK,
XE_RENDER_MASK_DEPTH,
XE_RENDER_MASK_RED,
XE_RENDER_MASK_GREEN,
XE_RENDER_MASK_BLUE,
XE_RENDER_MASK_ALPHA,
XE_RENDER_DITHER,
XE_RENDER_TEXTURING_2D,
XE_RENDER_NORMALIZE,
XE_RENDER_FACE_FRONT,
XE_RENDER_FACE_BACK,
XE_RENDER_FACE_FRONT_AND_BACK,
XE_RENDER_LIGHTING,
XE_RENDER_LIGHT_SOURCE,
XE_RENDER_LIGHT_AMBIENT,
XE_RENDER_LIGHT_DIFFUSE,
XE_RENDER_LIGHT_SPECULAR,
XE_RENDER_LIGHT_POSITION,
XE_RENDER_LIGHT_SPOT_DIRECTION,
XE_RENDER_LIGHT_SPOT_EXPONENT,
XE_RENDER_LIGHT_SPOT_CUTOFF,
XE_RENDER_LIGHT_MODEL_AMBIENT,
XE_RENDER_MATERIAL_AMBIENT,
XE_RENDER_MATERIAL_DIFFUSE,
XE_RENDER_MATERIAL_SPECULAR,
XE_RENDER_MATERIAL_EMISSION,
XE_RENDER_MATERIAL_SHININESS,
XE_RENDER_DEPTH_TEST,
XE_RENDER_DEPTH_TYPE,
XE_RENDER_DEPTH_NEVER,
XE_RENDER_DEPTH_LESS,
XE_RENDER_DEPTH_EQUAL,
XE_RENDER_DEPTH_LEQUAL,
XE_RENDER_DEPTH_GREATER,
XE_RENDER_DEPTH_NOTEQUAL,
XE_RENDER_DEPTH_GEQUAL,
XE_RENDER_DEPTH_ALWAYS,
XE_RENDER_ALPHA_TEST,
XE_RENDER_ALPHA_TYPE,
XE_RENDER_ALPHA_REF,
XE_RENDER_ALPHA_NEVER,
XE_RENDER_ALPHA_LESS,
XE_RENDER_ALPHA_EQUAL,
XE_RENDER_ALPHA_LEQUAL,
XE_RENDER_ALPHA_GREATER,
XE_RENDER_ALPHA_NOTEQUAL,
XE_RENDER_ALPHA_GEQUAL,
XE_RENDER_ALPHA_ALWAYS,
XE_RENDER_CULL_FACE,
XE_RENDER_CULL_TYPE,
XE_RENDER_CULL_FRONT,
XE_RENDER_CULL_BACK,
XE_RENDER_CULL_FRONT_AND_BACK,
XE_RENDER_BLEND,
XE_RENDER_BLEND_TYPE,
XE_RENDER_BLEND_SRC,
XE_RENDER_BLEND_DST,
XE_RENDER_BLEND_ZERO,
XE_RENDER_BLEND_ONE,
XE_RENDER_BLEND_SRC_COLOR,
XE_RENDER_BLEND_ONE_MINUS_SRC_COLOR,
XE_RENDER_BLEND_DST_COLOR,
XE_RENDER_BLEND_ONE_MINUS_DST_COLOR,
XE_RENDER_BLEND_SRC_ALPHA,
XE_RENDER_BLEND_ONE_MINUS_SRC_ALPHA,
XE_RENDER_BLEND_DST_ALPHA,
XE_RENDER_BLEND_ONE_MINUS_DST_ALPHA,
XE_RENDER_BLEND_SRC_ALPHA_SATURATE,
XE_RENDER_BLEND_CONSTANT_COLOR,
XE_RENDER_BLEND_ONE_MINUS_CONSTANT_COLOR,
XE_RENDER_BLEND_CONSTANT_ALPHA,
XE_RENDER_BLEND_ONE_MINUS_CONSTANT_ALPHA,
XE_RENDER_BLEND_EQUATION,
XE_RENDER_BLEND_ADD,
XE_RENDER_BLEND_SUBTRACT,
XE_RENDER_BLEND_REVERSE_SUBTRACT,
XE_RENDER_BLEND_MIN,
XE_RENDER_BLEND_MAX,
XE_RENDER_FOG,
XE_RENDER_FOG_COLOR,
XE_RENDER_FOG_START,
XE_RENDER_FOG_END,
XE_RENDER_FOG_DENSITY,
XE_RENDER_FOG_MODE,
XE_RENDER_FOG_TYPE,
XE_RENDER_FOG_DISTANCE,
XE_RENDER_FOG_COORD,
XE_RENDER_FOG_LINEAR,
XE_RENDER_FOG_EXP,
XE_RENDER_FOG_EXP2,
XE_RENDER_STENCIL_TEST,
XE_RENDER_STENCIL_CLEAR,
XE_RENDER_STENCIL_TYPE,
XE_RENDER_STENCIL_FUNC,
XE_RENDER_STENCIL_FUNC_NEVER,
XE_RENDER_STENCIL_FUNC_LESS,
XE_RENDER_STENCIL_FUNC_EQUAL,
XE_RENDER_STENCIL_FUNC_LEQUAL,
XE_RENDER_STENCIL_FUNC_GREATER,
XE_RENDER_STENCIL_FUNC_NOTEQUAL,
XE_RENDER_STENCIL_FUNC_GEQUAL,
XE_RENDER_STENCIL_FUNC_ALWAYS,
XE_RENDER_STENCIL_REF,
XE_RENDER_STENCIL_MASK,
XE_RENDER_STENCIL_OPERATION,
XE_RENDER_STENCIL_KEEP,
XE_RENDER_STENCIL_ZERO,
XE_RENDER_STENCIL_REPLACE,
XE_RENDER_STENCIL_INCR,
XE_RENDER_STENCIL_DECR,
XE_RENDER_STENCIL_INVERT,
XE_RENDER_ACCUM,
XE_RENDER_ACCUM_COLOR,
XE_RENDER_ACCUM_ACCUM,
XE_RENDER_ACCUM_LOAD,
XE_RENDER_ACCUM_RETURN,
XE_RENDER_ACCUM_MULT,
XE_RENDER_ACCUM_ADD,
XE_RENDER_SCISSOR,
XE_RENDER_SCISSOR_MODE,
XE_RENDER_POINT_SIZE,
XE_RENDER_POINT_SIZE_VERTEX_SHADER,
XE_RENDER_POINT_SIZE_MIN,
XE_RENDER_POINT_SIZE_MAX,
XE_RENDER_POINT_SPRITES_MODE,
XE_RENDER_POINT_SPRITES_COORD_REPLACE,
XE_RENDER_POINT_SMOOTH,
XE_RENDER_LINE_SMOOTH,
XE_RENDER_POLYGON_SMOOTH,
XE_HINT_FOG,
XE_HINT_PERSPECTIVE_CORRECTION,
XE_HINT_POINT_SMOOTH,
XE_HINT_LINE_SMOOTH,
XE_HINT_POLYGON_SMOOTH,
XE_HINT_NICEST,
XE_HINT_FASTEST,
XE_HINT_DONT_CARE,
XE_TEXTURE_PARAM_MIN_FILTER,
XE_TEXTURE_PARAM_MAG_FILTER,
XE_TEXTURE_PARAM_WRAP_S,
XE_TEXTURE_PARAM_WRAP_T,
XE_TEXTURE_PARAM_PRIORITY,
XE_TEXTURE_PARAM_NEAREST,
XE_TEXTURE_PARAM_LINEAR,
XE_TEXTURE_PARAM_NEAREST_MIPMAP_NEAREST,
XE_TEXTURE_PARAM_LINEAR_MIPMAP_NEAREST,
XE_TEXTURE_PARAM_NEAREST_MIPMAP_LINEAR,
XE_TEXTURE_PARAM_LINEAR_MIPMAP_LINEAR,
XE_TEXTURE_PARAM_REPEAT,
XE_TEXTURE_PARAM_CLAMP,
XE_TEXTURE_MODE_ADD,
XE_TEXTURE_MODE_MODULATE,
XE_TEXTURE_MODE_DECAL,
XE_TEXTURE_MODE_BLEND,
XE_TEXTURE_MODE_REPLACE,
XE_TEXTURE_MODE_COMBINE,
XE_TEXTURE_MULTI_MODE,
XE_TEXTURE_UNIT_COUNT,
XE_TEXTURE_WIDTH,
XE_TEXTURE_HEIGHT,
XE_TEXTURE_PIXELS_BUFFER,
XE_TEXTURE_PIXELS_SIZE,
XE_SCENE_COLOR,
XE_MATRIX_PROJECTION,
XE_MATRIX_MODELVIEW,
XE_MATRIX_TEXTURE,
XE_PHYSICAL_SUBSTANCE_ENERGY_LEVEL,
XE_PHYSICAL_SUBSTANCE_ENERGY_LEVEL_MODE,
XE_PHYSICAL_GRAVITY_MODE,
XE_PHYSICAL_GRAVITY_FACTOR,
XE_PHYSICAL_COVALENCE_FORCE_MODE,
XE_PHYSICAL_COVALENCE_FORCE_FIRST_STREAM,
XE_PHYSICAL_COVALENCE_FORCE_LAST_STREAM,
XE_PHYSICAL_COVALENCE_FORCE_ITERATIVE_STREAM,
XE_PHYSICAL_COVALENCE_FORCE_BREAK_MODE,
XE_PHYSICAL_COVALENCE_FORCE_BREAK_TESSELLATE,
XE_PHYSICAL_FORCE_MODE,
XE_PHYSICAL_GLOBAL_FORCE_MODE,
XE_PHYSICAL_BLACK_HOLE_MODE,
XE_PHYSICAL_RANGE_COLLISION_MODE,
XE_PHYSICAL_RANGE_COLLISION_TYPE,
XE_PHYSICAL_RANGE_COLLISION_STANDARD_MOVE,
XE_PHYSICAL_RANGE_COLLISION_TEMPORARY_MOVE,
XE_PHYSICAL_SURFACE_COLLISION_MODE,
XE_PHYSICAL_SURFACE_COLLISION_MODE_2D,
XE_PHYSICAL_SURFACE_COLLISION_2D_AXIS_XY,
XE_PHYSICAL_SURFACE_COLLISION_2D_AXIS_YZ,
XE_PHYSICAL_SURFACE_COLLISION_2D_AXIS_ZX,
XE_PHYSICAL_SURFACE_COLLISION_TYPE,
XE_PHYSICAL_SURFACE_COLLISION_STANDARD_MOVE,
XE_PHYSICAL_SURFACE_COLLISION_TEMPORARY_MOVE,
XE_PHYSICAL_SURFACE_COLLISION_SAMPLE,
XE_PHYSICAL_INERTION_MODE,
XE_PHYSICAL_INERTION_FRICTION,
XE_PHYSICAL_INERTION_RANGE,
XE_PHYSICAL_INERTION_SURFACE,
XE_PHYSICAL_INERTION_FORCE,
XE_PHYSICAL_INERTION_GLOBAL_FORCE,
XE_PHYSICAL_INERTION_WAVE_FORCE,
XE_PHYSICAL_INERTION_MOVE,
XE_PHYSICAL_INERTION_FACTOR,
XE_PHYSICAL_INERTION_LIMITATION,
XE_PHYSICAL_WAVE_FORCE_MODE,
XE_PHYSICAL_GENERATE_TESSELLATION,
XE_PHYSICAL_GENERATE_SUBSTANCE_PROC,
XE_PHYSICAL_GENERATE_RAY_PROC,
XE_PHYSICAL_GENERATE_COVALENCE_FORCE_PROC,
XE_PHYSICAL_GENERATE_FORCE_PROC,
XE_PHYSICAL_GENERATE_SURFACE_PROC,
XE_PHYSICAL_GENERATE_PARTICLE_PROC,
XE_PHYSICAL_GENERATE_GLOBAL_FORCE_PROC,
XE_PHYSICAL_GENERATE_BLACK_HOLE_PROC,
XE_PHYSICAL_GENERATE_WAVE_FORCE_PROC,
XE_SUBSTANCE_OBJECT,
XE_SUBSTANCE_POSITION,
XE_SUBSTANCE_LAST_POSITION,
XE_SUBSTANCE_RANGE,
XE_SUBSTANCE_MASS,
XE_SUBSTANCE_ENERGY,
XE_SUBSTANCE_SOLID,
XE_SUBSTANCE_INERTION,
XE_RAY_POSITION,
XE_RAY_DIRECTION,
XE_RAY_ANGLE,
XE_RAY_ENERGY,
XE_RAY_FREQUENCY,
XE_COVALENCE_FORCE_SUBSTANCE_1,
XE_COVALENCE_FORCE_SUBSTANCE_2,
XE_COVALENCE_FORCE_FORCE,
XE_COVALENCE_FORCE_RESILIENCE,
XE_COVALENCE_FORCE_RANGE,
XE_COVALENCE_FORCE_SOLID,
XE_COVALENCE_FORCE_SOLID_ALWAYS,
XE_COVALENCE_FORCE_SOLID_TEMPORARY,
XE_COVALENCE_FORCE_SOLID_NEVER,
XE_FORCE_POSITION,
XE_FORCE_DIRECTION,
XE_FORCE_FORCE,
XE_FORCE_SPEED,
XE_FORCE_ANCHOR,
XE_FORCE_ANCHOR_DIRECTION,
XE_FORCE_RICOCHET,
XE_FORCE_RANGE,
XE_SURFACE_SUBSTANCE_1,
XE_SURFACE_SUBSTANCE_2,
XE_SURFACE_SUBSTANCE_3,
XE_SURFACE_TEXTURE,
XE_SURFACE_TEXTURE_TYPE,
XE_SURFACE_ORDER,
XE_SURFACE_COORD_SUBSTANCE_1,
XE_SURFACE_COORD_SUBSTANCE_2,
XE_SURFACE_COORD_SUBSTANCE_3,
XE_SURFACE_DENSITY,
XE_SURFACE_ORIENTATION,
XE_SURFACE_ORIENTATION_SINGLE,
XE_SURFACE_ORIENTATION_DOUBLE,
XE_PARTICLE_SUBSTANCE,
XE_PARTICLE_SIZE,
XE_PARTICLE_TEXTURE,
XE_PARTICLE_TEXTURE_TYPE,
XE_GLOBAL_FORCE_POSITION,
XE_GLOBAL_FORCE_DIRECTION,
XE_GLOBAL_FORCE_FORCE,
XE_BLACK_HOLE_POSITION,
XE_BLACK_HOLE_FORCE,
XE_BLACK_HOLE_RANGE,
XE_BLACK_HOLE_ANCHOR,
XE_WAVE_FORCE_POSITION,
XE_WAVE_FORCE_FORCE,
XE_WAVE_FORCE_RANGE,
XE_WAVE_FORCE_LENGTH,
XE_WAVE_FORCE_SPEED,
XE_WAVE_FORCE_ORIENTATION,
XE_WAVE_FORCE_ORIENTATION_IN,
XE_WAVE_FORCE_ORIENTATION_OUT,
XE_WAVE_FORCE_ORIENTATION_INNER,
XE_WAVE_FORCE_ORIENTATION_OUTER,
XE_PSYCHE_NEURON,
XE_PSYCHE_NEURON_LENGTH,
XE_PSYCHE_NEURON_GATE,
XE_PSYCHE_NEURON_POSITION,
XE_PSYCHE_NEURON_FIRST,
XE_PSYCHE_NEURON_LAST,
XE_PSYCHE_NEURON_NEXT,
XE_PSYCHE_NEURON_PREV,
XE_PSYCHE_DETECTOR,
XE_PSYCHE_DETECTOR_SIGNAL,
XE_PSYCHE_DETECTOR_POSITION,
XE_PSYCHE_DETECTOR_FIRST,
XE_PSYCHE_DETECTOR_LAST,
XE_PSYCHE_DETECTOR_NEXT,
XE_PSYCHE_DETECTOR_PREV,
XE_PSYCHE_EFFECTOR,
XE_PSYCHE_EFFECTOR_LENGTH,
XE_PSYCHE_EFFECTOR_SIGNAL,
XE_PSYCHE_EFFECTOR_POSITION,
XE_PSYCHE_EFFECTOR_FIRST,
XE_PSYCHE_EFFECTOR_LAST,
XE_PSYCHE_EFFECTOR_NEXT,
XE_PSYCHE_EFFECTOR_PREV,
XE_PSYCHE_SIGNAL,
XE_PSYCHE_SIGNAL_SIGNAL,
XE_PSYCHE_SIGNAL_POSITION,
XE_PSYCHE_SIGNAL_FIRST,
XE_PSYCHE_SIGNAL_LAST,
XE_PSYCHE_SIGNAL_NEXT,
XE_PSYCHE_SIGNAL_PREV,
XE_PSYCHE_SYNAPSIS,
XE_PSYCHE_SYNAPSIS_GATE,
XE_PSYCHE_SYNAPSIS_POSITION,
XE_PSYCHE_SYNAPSIS_FIRST,
XE_PSYCHE_SYNAPSIS_LAST,
XE_PSYCHE_SYNAPSIS_NEXT,
XE_PSYCHE_SYNAPSIS_PREV,
XE_LOGGER_FILE,
XE_AREA_MODE,
XE_AREA_X1,
XE_AREA_Y1,
XE_AREA_Z1,
XE_AREA_X2,
XE_AREA_Y2,
XE_AREA_Z2,
XE_AREA_PROPERTIES,
XE_PHYSICAL_PROCEDURE,
XE_V3,
XE_C3_V3,
XE_C4_N3_V3,
XE_T4_C4_N3_V4,
XE_SHADER_VP_ARB,
XE_SHADER_FP_ARB,
XE_SHADER_VP_SL,
XE_SHADER_FP_SL,
XE_SHADER_PROGRAM_SL,
XE_SHADER_VP_ARB_PROFILE,
XE_SHADER_FP_ARB_PROFILE,
XE_SHADER_SL_PROFILE,
XE_RENDERTARGET_WINDOW_HANDLE,
XE_RENDERTARGET_DISPLAY_CONTEXT,
XE_RENDERTARGET_RENDER_CONTEXT,
XE_RENDERTARGET_X,
XE_RENDERTARGET_Y,
XE_RENDERTARGET_WIDTH,
XE_RENDERTARGET_HEIGHT,
XE_RENDERTARGET_ANGLE,
XE_RENDERTARGET_ZNEAR,
XE_RENDERTARGET_ZFAR,
XE_RENDERTARGET_ASPECT,
XE_RENDERTARGET_DRAW_MODE,
XE_FRAMEBUFFER_WIDTH,
XE_FRAMEBUFFER_HEIGHT,
XE_FRAMEBUFFER_TEXTURE,
XE_FRAMEBUFFER_TEXTURE_DEPTH,
XE_VERTEXBUFFER_ARRAY,
XE_VERTEXBUFFER_ELEMENT,
XE_VERTEXBUFFER_STATIC_DRAW,
XE_VERTEXBUFFER_STATIC_READ,
XE_VERTEXBUFFER_STATIC_COPY,
XE_VERTEXBUFFER_DYNAMIC_DRAW,
XE_VERTEXBUFFER_DYNAMIC_READ,
XE_VERTEXBUFFER_DYNAMIC_COPY,
XE_VERTEXBUFFER_STREAM_DRAW,
XE_VERTEXBUFFER_STREAM_READ,
XE_VERTEXBUFFER_STREAM_COPY,
XE_VERTEXBUFFER_READ,
XE_VERTEXBUFFER_WRITE,
XE_VERTEXBUFFER_READWRITE,
XE_REGISTER_ON_TIME_AXIS,
XE_PHYSICAL_TIME,
XE_PHYSICAL_TIME_FACTOR,
XE_CUSTOM_VERTEX,
XE_CUSTOM_COLOR,
XE_CUSTOM_COORD,
XE_CUSTOM_NORMAL,
XE_CUSTOM_ATTRIBUTE,
XE_ESTATE_END
};

} // XeCore

#endif // _XENON_CORE_2_H_
